### ISSUE TITLE
3.5.0 has a compile error with Igniter

### ISSUE THREAD

**Issue by paulswartz** [erlef/oidcc#438]
### oidcc version

3.5.0

### Erlang version

26.2.1

### Elixir version

1.15.8

### Summary

Oidcc 3.5.0 fails to compile with an error about Igniter not being loaded.  I'll try to look into it later, but I don't have time right at the moment.

### Current behavior

```
==> oidcc
Compiling 17 files (.erl)
Compiling 16 files (.ex)
error: module Igniter.Mix.Task is not loaded and could not be found
  lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex:32: Mix.Tasks.Oidcc.Gen.ProviderConfigurationWorker (module)
== Compilation error in file lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex ==
** (CompileError) lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex: cannot compile module Mix.Tasks.Oidcc.Gen.ProviderConfigurationWorker (errors have been logged)
    (elixir 1.15.7) expanding macro: Kernel.use/1
    lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex:32: Mix.Tasks.Oidcc.Gen.ProviderConfigurationWorker (module)
    (elixir 1.15.7) expanding macro: Kernel.if/2
    lib/mix/tasks/oidcc.gen.provider_configuration_worker.ex:31: Mix.Tasks.Oidcc.Gen.ProviderConfigurationWorker (module)
could not compile dependency :oidcc, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile oidcc --force", update it with "mix deps.update oidcc" or clean it with "mix deps.clean oidcc"
```
I suspect this was introduced by #379.

### How to reproduce

Use `oidcc` as an Elixir library, as with UeberauthOidcc.

### Expected behavior

Normal compliation. 3.3.0 did not have this issue.
